# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://kkolli.github.io/MathGame
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
